"""empty message

Revision ID: bbe1c016b3a6
Revises: 
Create Date: 2021-01-07 13:01:53.977783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbe1c016b3a6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('old_name', sa.String(), nullable=True),
    sa.Column('teacher_1', sa.Integer(), nullable=False),
    sa.Column('number_students', sa.Integer(), nullable=True),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('cost', sa.Integer(), nullable=True),
    sa.Column('location', sa.Integer(), nullable=True),
    sa.Column('teacher_name', sa.String(), nullable=True),
    sa.Column('teacher_surname', sa.String(), nullable=True),
    sa.Column('type_of_course', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('loc', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('all__capital__expenditure',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('total_sum', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('all__charity__sums',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bank_charity', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('all_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('all_groups', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('all_overhead',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('total_sum', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('all_students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('students', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('all_teachers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teachers', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('all_withdrawal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('total_sum', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attendance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('present', sa.DateTime(), nullable=True),
    sa.Column('apset', sa.DateTime(), nullable=True),
    sa.Column('darsga_tayyorgarligi', sa.Integer(), nullable=True),
    sa.Column('lugat', sa.Integer(), nullable=True),
    sa.Column('darsda_qatnashishi', sa.Integer(), nullable=True),
    sa.Column('ortacha_baho', sa.Integer(), nullable=True),
    sa.Column('fan', sa.String(), nullable=True),
    sa.Column('for_sabab', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bank',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cash', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('capital_expenditure',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item', sa.String(), nullable=True),
    sa.Column('number_items', sa.Integer(), nullable=True),
    sa.Column('amount_item', sa.Integer(), nullable=True),
    sa.Column('bought_data', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('deleted_students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('student_name', sa.String(), nullable=True),
    sa.Column('student_surname', sa.String(), nullable=True),
    sa.Column('student_phone', sa.String(), nullable=True),
    sa.Column('student_parent_phone', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('due_days',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('img_due_days', sa.String(), nullable=False),
    sa.Column('group_id_student', sa.Integer(), nullable=False),
    sa.Column('id_of_student', sa.Integer(), nullable=False),
    sa.Column('date_of_absent', sa.DateTime(), nullable=False),
    sa.Column('reason_due', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('overhead',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('quantity', sa.String(), nullable=True),
    sa.Column('sum', sa.Integer(), nullable=True),
    sa.Column('payed_data', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reason_apset_days',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('img_due_days', sa.String(), nullable=False),
    sa.Column('reason_due', sa.String(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('date_abset', sa.DateTime(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student_cash',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('student_name', sa.String(), nullable=True),
    sa.Column('student_surname', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('debt', sa.Integer(), nullable=True),
    sa.Column('payment', sa.Integer(), nullable=True),
    sa.Column('result', sa.Integer(), nullable=True),
    sa.Column('payment_data', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teacher_cash',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.Column('teacher_name', sa.String(), nullable=True),
    sa.Column('teacher_surname', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('salary', sa.Integer(), nullable=True),
    sa.Column('payment', sa.Integer(), nullable=True),
    sa.Column('result', sa.Integer(), nullable=True),
    sa.Column('payment_data', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('withdrawal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('who', sa.String(), nullable=True),
    sa.Column('why', sa.String(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Teachers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teacher', sa.Boolean(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('surname', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('age', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('locations', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('for_group', sa.Boolean(), nullable=True),
    sa.Column('otasining_ismi', sa.String(), nullable=True),
    sa.Column('salary', sa.Integer(), nullable=True),
    sa.Column('number_groups', sa.Integer(), nullable=True),
    sa.Column('group1', sa.Integer(), nullable=True),
    sa.Column('group2', sa.Integer(), nullable=True),
    sa.Column('group3', sa.Integer(), nullable=True),
    sa.Column('group4', sa.Integer(), nullable=True),
    sa.Column('group5', sa.Integer(), nullable=True),
    sa.Column('group6', sa.Integer(), nullable=True),
    sa.Column('group7', sa.Integer(), nullable=True),
    sa.Column('group8', sa.Integer(), nullable=True),
    sa.Column('group9', sa.Integer(), nullable=True),
    sa.Column('group10', sa.Integer(), nullable=True),
    sa.Column('photo', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['locations'], ['Locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('xojakent_admin', sa.Boolean(), nullable=True),
    sa.Column('gazalkent_admin', sa.Boolean(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('surname', sa.String(), nullable=True),
    sa.Column('born_date', sa.DateTime(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('mother_phone', sa.String(), nullable=True),
    sa.Column('father_phone', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('director', sa.Boolean(), nullable=True),
    sa.Column('subject_1', sa.String(), nullable=True),
    sa.Column('subject_2', sa.String(), nullable=True),
    sa.Column('subject_3', sa.String(), nullable=True),
    sa.Column('for_group', sa.Boolean(), nullable=True),
    sa.Column('group1', sa.Integer(), nullable=True),
    sa.Column('group2', sa.Integer(), nullable=True),
    sa.Column('group3', sa.Integer(), nullable=True),
    sa.Column('locations', sa.Integer(), nullable=True),
    sa.Column('money', sa.Integer(), nullable=True),
    sa.Column('attendance', sa.Boolean(), nullable=True),
    sa.Column('charity', sa.Integer(), nullable=True),
    sa.Column('photo', sa.String(), nullable=True),
    sa.Column('otasining_ismi', sa.String(), nullable=True),
    sa.Column('for_moved', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['locations'], ['Locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student')
    op.drop_table('Teachers')
    op.drop_table('withdrawal')
    op.drop_table('teacher_cash')
    op.drop_table('student_cash')
    op.drop_table('reason_apset_days')
    op.drop_table('overhead')
    op.drop_table('due_days')
    op.drop_table('deleted_students')
    op.drop_table('capital_expenditure')
    op.drop_table('bank')
    op.drop_table('attendance')
    op.drop_table('all_withdrawal')
    op.drop_table('all_teachers')
    op.drop_table('all_students')
    op.drop_table('all_overhead')
    op.drop_table('all_groups')
    op.drop_table('all__charity__sums')
    op.drop_table('all__capital__expenditure')
    op.drop_table('Locations')
    op.drop_table('Groups')
    # ### end Alembic commands ###
